permalink: /:categories/:title
title: 'WiseVoter'
encoding: 'utf-8'

# All WiseVoter specific configurations are namespaced into this hash
#
WV :
  version : 0.0.5

  # Setting for analytics include
  analytics :
    google :
      tracking_id : 'UA-8311051-1'

# links to include in top navigation
links:
  - title: Home
    url: /
  - title: Articles
    url: /articles.html
  - title: Constituencies
    url: /constituencies.html
  - title: Politicians
    url: /politicians.html
  - title: Parties
    url: /parties.html
  - title: Issues
    url: /issues.html

blogroll:
  - title: Ballot.in
    url: http://www.ballot.in

